/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package it.unibas.questionari.vista;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import it.unibas.questionari.Applicazione;
import it.unibas.questionari.Costanti;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author francesco
 */
public class Frame extends javax.swing.JFrame {

    static {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }

        Applicazione.getInstance().getModello().putBean(Costanti.TEMA, Costanti.TEMA_LIGHT);
    }

    public void aggiornaTema() throws UnsupportedLookAndFeelException {
        String tema = (String) Applicazione.getInstance().getModello().getBean(Costanti.TEMA);
//        if (tema.equals(Costanti.TEMA_LIGHT)) {
//            UIManager.setLookAndFeel(new FlatLightLaf());
//        } else {
//            UIManager.setLookAndFeel(new FlatDarkLaf());
//        }
        
        UIManager.setLookAndFeel(tema.equals(Costanti.TEMA_LIGHT) ? new FlatLightLaf() : new FlatDarkLaf());
        SwingUtilities.updateComponentTreeUI(this);
        this.pack();
    }

    /**
     * Creates new form Frame
     */
    public Frame() {
    }

    public void inizializza() {

        initComponents();
        impostaAzioni();
        this.setContentPane(new JScrollPane(Applicazione.getInstance().getVistaPrincipale()));
        this.pack();
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    private void impostaAzioni() {
        menuCarica.setAction(Applicazione.getInstance().getControlloMenu().getAzioneCarica());
        menuEsci.setAction(Applicazione.getInstance().getControlloMenu().getAzioneEsci());
        menuVerifica.setAction(Applicazione.getInstance().getControlloMenu().getAzioneVerificaCompilazioni());
        menuCambiaTema.setAction(Applicazione.getInstance().getControlloMenu().getAzioneCambiaTema());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu1 = new javax.swing.JMenu();
        menuCarica = new javax.swing.JMenuItem();
        menuVerifica = new javax.swing.JMenuItem();
        javax.swing.JPopupMenu.Separator jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuEsci = new javax.swing.JMenuItem();
        javax.swing.JMenu jMenu2 = new javax.swing.JMenu();
        menuCambiaTema = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Questionari");

        jMenu1.setText("File");

        menuCarica.setText("Carica");
        jMenu1.add(menuCarica);

        menuVerifica.setText("Verifica");
        jMenu1.add(menuVerifica);
        jMenu1.add(jSeparator1);

        menuEsci.setText("Esci");
        jMenu1.add(menuEsci);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Modifica");

        menuCambiaTema.setText("Cambia tema");
        jMenu2.add(menuCambiaTema);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1015, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem menuCambiaTema;
    private javax.swing.JMenuItem menuCarica;
    private javax.swing.JMenuItem menuEsci;
    private javax.swing.JMenuItem menuVerifica;
    // End of variables declaration//GEN-END:variables

    public void mostraMessaggioErrore(String messaggio) {
        JOptionPane.showMessageDialog(this, messaggio, "ERRORE", JOptionPane.ERROR_MESSAGE);
    }

    public void mostraMessaggio(String messaggio) {
        JOptionPane.showMessageDialog(this, messaggio);
    }
}
