package it.unibas.questionari.vista;

import it.unibas.questionari.Applicazione;
import it.unibas.questionari.Costanti;
import it.unibas.questionari.modello.Questionario;
import java.util.List;

/**
 *
 * @author francesco
 */
public class VistaPrincipale extends javax.swing.JPanel {

    /**
     * Creates new form VistaPrincipale
     */
    public VistaPrincipale() {
    }

    public void inizializza() {
        initComponents();
        impostaAzioni();
        inizializzaCampi();
    }

    private void impostaAzioni() {
        bottoneCerca.setAction(Applicazione.getInstance().getControlloPrincipale().getAzioneCerca());
        bottoneVerificaQuestionario.setAction(Applicazione.getInstance().getControlloPrincipale().getAzioneVerificaQuestionario());
    }

    private void inizializzaCampi() {
        this.comboArgomento.removeAllItems();
        this.comboArgomento.addItem("");
        this.comboArgomento.addItem(Costanti.STORIA);
        this.comboArgomento.addItem(Costanti.ITALIANO);
        this.comboArgomento.addItem(Costanti.GEOGRAFIA);

        this.tabellaQuestionari.setModel(new ModelloTabellaQuestionari());
    }

    public String getCampoArgomento() {
        return (String) comboArgomento.getSelectedItem();
    }

    public int getCampoDifficolta() {
        return (int) campoDifficolta.getValue();
    }

    public Integer getQuestionarioSelezionato() {
        int selezionato = tabellaQuestionari.getSelectedRow();
        if (selezionato != -1) {
            return selezionato;
        }
        return null;
    }

    public void aggiornaDati() {
        ModelloTabellaQuestionari modelloTabella = (ModelloTabellaQuestionari) this.tabellaQuestionari.getModel();
        modelloTabella.setQuestionari((List<Questionario>) Applicazione.getInstance().getModello().getBean(Costanti.LISTA_QUESTIONARI));
        modelloTabella.aggiornaContenuto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        comboArgomento = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        campoDifficolta = new javax.swing.JSpinner();
        bottoneCerca = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tabellaQuestionari = new javax.swing.JTable();
        bottoneVerificaQuestionario = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ricerca questionari"));

        jLabel1.setText("Argomento");

        comboArgomento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Difficolta'");

        campoDifficolta.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        bottoneCerca.setText("Cerca");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboArgomento, 0, 186, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDifficolta, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bottoneCerca, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboArgomento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(campoDifficolta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bottoneCerca))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tabellaQuestionari.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        tabellaQuestionari.setForeground(new java.awt.Color(51, 51, 255));
        tabellaQuestionari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabellaQuestionari);

        bottoneVerificaQuestionario.setText("Verifica");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bottoneVerificaQuestionario, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bottoneVerificaQuestionario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottoneCerca;
    private javax.swing.JButton bottoneVerificaQuestionario;
    private javax.swing.JSpinner campoDifficolta;
    private javax.swing.JComboBox<String> comboArgomento;
    private javax.swing.JTable tabellaQuestionari;
    // End of variables declaration//GEN-END:variables

}
